name: paytr_test_case
description: PayTR Test Case

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  riverpod_annotation: ^2.1.5
  auto_route: ^7.8.3
  dio: ^5.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  reactive_forms: ^16.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dependency_overrides:
  test_api: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  random_string: ^2.3.1
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  json_serializable: ^6.7.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
